### PR TITLE
Refactor, add entity support and introduce breaking changes

### PR DESCRIPTION
**Pull request by grantholle**
This is quite extensive and introduces several breaking changes. Looking forward to working through the details. I wasn't able to test some things due to either poor documentation or limitations on my Bullhorn API account. I've added tests where I could.

Since Bullhorn's api is built around entities and they all share the same REST functionality, I've refactored the magic methods to simply set the type of the entity of a general Entity object and perform the api functionality on it. There's no need to create a specific class for each of Bullhorn's entity types.

```php
// JobOrders
$client->JobOrders->search([]);

// Lead
$client->Lead->create([]);
```

This way, adding functionality to one entity adds it to all. It's basically just sugar around doing manual `request` calls.

I refactored event subscriptions to be handled differently.

```php
// Create a subscription
$createdSub = $client->eventSubscription('MySub')
    ->create(['Lead', 'Candidate'], ['INSERT', 'UPDATE']);

// Get the subscription results
$results = $client->eventSubscription('MySub')->get(); 

// Delete the subscription
$client->eventSubscription('MySub')->delete();
``` 

I've also added docblocks and type hints to functions.

### CODE REVIEW

**Comment by KajdeMunter** [comment]
Any plans of merging this? I like it.

**Comment by jonathanraftery** [comment]
@grantholle and @KajdeMunter I'm spending less and less time in the PHP community these days. I'd like to open this up for other maintainers to prevent quality updates like this from being held up (I like it, but don't have the time to thoroughly vet it). Would either of you be interested in taking over as a maintainer?

**Comment by grantholle** [comment]
Yeah I could be a maintainer

**Comment by KajdeMunter** [comment]
I can be as well

**Comment by jonathanraftery** [comment]
The client has now been updated with many of these features implemented in other ways, as well as improvements such as not using magic getters and better tests.

Thanks for the input!

**Pull request closed without merging**
