### PR TITLE
Dev refresh session

### PR DESCRIPTION
**Pull request by 40katty04**

### CODE REVIEW

**Comment by willnjl** [comment]
please merge

**Comment by 40katty04** [comment]
> please merge

It is merged, I'm using it:

**Comment by jonathanraftery** [comment]
It is not merged. Using your fork is an option, though typically it's best to keep dependency on the original package.

There are some quality issues with this merge request that will be reviewed/corrected soon.

**Comment by 40katty04** [comment]
Okay, I will merge. For clarify: I got another format message only from one Bullhrn Entity. I don't remember what it was, but I guess it was when I trying to create or update JobSubmission.

**Review by jonathanraftery — APPROVED** [review]

**Pull request merged**
